# Generated by Django 4.0.4 on 2022-05-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='extra',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='doctor',
            name='extra',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
