# Generated by Django 4.0.3 on 2022-06-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentprocedure',
            name='resultText',
            field=models.TextField(default=None, null=True),
        ),
    ]
