# Generated by Django 4.0.3 on 2022-05-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='specialization',
            field=models.CharField(default='', max_length=400),
        ),
    ]
