# Generated by Django 4.0.3 on 2022-05-06 03:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), null=True, size=2)),
                ('tuesday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), null=True, size=2)),
                ('wednesday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), null=True, size=2)),
                ('thursday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), null=True, size=2)),
                ('friday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), null=True, size=2)),
                ('saturday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), null=True, size=2)),
                ('sunday', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), null=True, size=2)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='med.doctor')),
            ],
        ),
    ]
