# Generated by Django 4.0.4 on 2022-05-25 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='passport_series',
        ),
    ]
