# Generated by Django 4.0.4 on 2022-05-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_clinic_extra_doctor_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='extra',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='extra',
            field=models.CharField(default='Нет дополнительной информации', max_length=1000),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='extra',
            field=models.CharField(default='Нет дополнительной информации', max_length=1000),
        ),
    ]
