# Generated by Django 4.0.3 on 2022-05-20 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_alter_currentprocedure_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
