# Generated by Django 4.0.3 on 2022-06-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_currentprocedure_resulttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentprocedure',
            name='resultImage',
            field=models.ImageField(default=None, null=True, upload_to='procResults/'),
        ),
    ]
