# Generated by Django 4.0.4 on 2022-05-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_remove_doctor_passport_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='addressLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
