# Generated by Django 4.0.3 on 2022-03-12 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
