# Generated by Django 4.0.3 on 2022-05-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
