# Generated by Django 4.0.3 on 2022-05-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_user_patronymic_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clinic',
            name='specialization',
            field=models.CharField(default='', max_length=60),
        ),
    ]
