# Generated by Django 4.0.4 on 2022-05-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_patient_extra_alter_clinic_extra_alter_doctor_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='avatars/'),
        ),
    ]
