# Generated by Django 4.0.3 on 2022-05-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_alter_clinic_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='specialization',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
