# Generated by Django 4.0.4 on 2022-05-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='specialization',
            field=models.CharField(default='Пациент', max_length=200),
        ),
    ]
