# Generated by Django 4.0.3 on 2022-05-10 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0004_alter_clinic_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=-1)),
                ('clinic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med.clinic')),
                ('doctor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med.doctor')),
                ('patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('procedure', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='med.procedure')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med.treatment')),
            ],
        ),
    ]
