# Generated by Django 4.0.3 on 2022-05-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0005_alter_procedure_name_treatment_currentprocedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic',
            field=models.ManyToManyField(to='med.clinic'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='complaint',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='symptoms',
            field=models.TextField(default=None, null=True),
        ),
    ]
