# Generated by Django 4.0.3 on 2022-05-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0006_doctor_clinic_treatment_complaint_treatment_symptoms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='clinic',
            new_name='clinics',
        ),
    ]
