# Generated by Django 4.0.3 on 2022-04-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0006_event_notification_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Доктор'},
        ),
    ]
