# Generated by Django 4.0.4 on 2022-05-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ava',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
