# Generated by Django 4.0.3 on 2022-04-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0006_event'),
        ('med', '0007_alter_doctor_options'),
    ]

    operations = [
    ]
