# Generated by Django 4.0.4 on 2022-05-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0008_patient_ava'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='clinic',
            name='ava',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='ava',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
