# Generated by Django 4.0.3 on 2022-04-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0008_merge_0006_event_0007_alter_doctor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='', max_length=20),
        ),
    ]
