# Generated by Django 4.0.3 on 2022-05-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0009_remove_user_avatar_clinic_ava_doctor_ava'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='ava',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='ava',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ava',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='specialization',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.jpg', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='extra',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='specialization',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='extra',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='extra',
            field=models.TextField(default=''),
        ),
    ]
